CREATE TABLE `t_userinfo` (
  `f_id` int(11) NOT NULL AUTO_INCREMENT COMMENT '用户id(自增)',
  `f_nickname` varchar(50) DEFAULT NULL COMMENT '昵称',
  `f_mobile` varchar(50) NOT NULL COMMENT '用户手机',
  `f_headimages` varchar(200) DEFAULT NULL COMMENT '头像地址',
  `f_lastdevice` varchar(200) DEFAULT NULL COMMENT '用户最近使用的设备',
  `f_regtime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '用户注册时间',
  `f_lasttime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`f_id`),
  UNIQUE KEY `f_uid` (`f_uid`),
  UNIQUE KEY `f_mobile` (`f_mobile`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `t_zq_matches_zx` (
  `f_id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID(自增)',
  `f_expectdate` varchar(100) NOT NULL COMMENT '资讯期号日期',
  `f_zxmatchid` int(10) NOT NULL COMMENT '资讯比赛场次ID',
  `f_leagueid` int(10) NOT NULL COMMENT '联赛ID',
  `f_homesxname` varchar(100) NOT NULL COMMENT '主队简称',
  `f_hometeamid` varchar(100) NOT NULL COMMENT '主队资讯ID',
  `f_awaysxname` varchar(100) NOT NULL COMMENT '客队简称',
  `f_awayteamid` varchar(100) NOT NULL COMMENT '客队资讯ID',
  `f_matchtime` timestamp NOT NULL COMMENT '比赛时间',
  `f_status` int(10) DEFAULT '0' COMMENT '比赛状态(0-未开始,1-进行中,2-正常结束,3-异常结束)',
  `f_status_desc` varchar(100) DEFAULT '' COMMENT '当前状态描述(0-未开始,1-上半场,2-中场,3-下半场,4-完场,5-取消,6-改期,7-腰斩,8-中断,9-待定,10-加时赛开始,11-加时结束,12-点球开始,13-点球结束)',
  `f_matchround` varchar(100) DEFAULT NULL COMMENT '当前轮次',
  `f_homescore` int(10) DEFAULT '-1' COMMENT '主队全场比分',
  `f_awayscore` int(10) DEFAULT '-1' COMMENT '客队全场比分',
  `f_homehalfscore` int(10) DEFAULT '-1' COMMENT '主队半场比分',
  `f_awayhalfscore` int(10) DEFAULT '-1' COMMENT '客队半场比分',
  `f_homescore_extra` int(10) DEFAULT '-1' COMMENT '主队加时比分',
  `f_awayscore_extra` int(10) DEFAULT '-1' COMMENT '客队加时比分',
  `f_homescore_spotkick` int(10) DEFAULT '-1' COMMENT '主队点球比分',
  `f_awayscore_spotkick` int(10) DEFAULT '-1' COMMENT '客队点球比分',
  `f_match_at` int(10) DEFAULT '-1' COMMENT '比赛直播进行时间点(单位/秒)',
  `f_addtime` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '添加时间',
  `f_updatetime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`f_id`),
  UNIQUE KEY `u_zq_matches_zx` (`f_zxmatchid`)
) ENGINE=InnoDB AUTO_INCREMENT=11493 DEFAULT CHARSET=utf8

CREATE TABLE DEBAO.T_USERINFO_1
(
  UI_ID           NUMBER(10)                    NOT NULL,
  UI_ACCTNUMBER   NUMBER,
  UI_USERNAME     VARCHAR2(50 BYTE)             NOT NULL,
  UI_USERMONEY    NUMBER(19,4)                  DEFAULT 0                     NOT NULL,
  UI_FREEZEMONEY  NUMBER(19,4)                  DEFAULT 0,
  UI_COMEFROM     VARCHAR2(20 BYTE)             DEFAULT '500WAN',
  UI_USERTYPE     NUMBER(10)                    DEFAULT 0                     NOT NULL,
  UI_LOCKTYPE     NUMBER                        DEFAULT 0,
  UI_CARNUMBER    VARCHAR2(72 BYTE),
  UI_BANKNAME     VARCHAR2(255 BYTE),
  UI_CAROFBANK    NUMBER(10)                    DEFAULT 0,
  UI_IDCODE       VARCHAR2(50 BYTE),
  UI_TRUENAME     VARCHAR2(1000 BYTE),
  UI_PROVINCE     VARCHAR2(20 BYTE),
  UI_CITY         VARCHAR2(20 BYTE),
  UI_ADDRESS      VARCHAR2(100 BYTE),
  UI_PHONE        VARCHAR2(50 BYTE),
  UI_ZIPCODE      VARCHAR2(50 BYTE),
  UI_BIRTHDAY     VARCHAR2(100 BYTE),
  UI_SEX          NUMBER(10)                    DEFAULT 1,
  UI_EMAIL        VARCHAR2(50 BYTE),
  UI_CHKUSERNAME  VARCHAR2(50 BYTE)             NOT NULL,
  UI_BANKCODE     VARCHAR2(10 BYTE),
  UI_COUNTYCODE   VARCHAR2(10 BYTE),
  UI_RETIME       DATE                          DEFAULT SYSDATE,
  UI_LASTTIME     DATE,
  UI_MAILCHECK    NUMBER(10)                    DEFAULT '0'
)